### ISSUE TITLE
Database Error setting is not working

### ISSUE THREAD

**Issue by daomapsieucap** [daomapsieucap/fiber-admin#10]
All the logo / image settings in Database Error options didn't work when the site URL is updated.

**Comment by phongkhuu115** [comment]
Temporarily, I'm going to test on my local machine, since it's much easier for me to change the site URL, all I need is to move it to another folder. But I will update all my progress on GitHub.

The current solution is to see if we can use a relative path instead of using the `content_url`

**Comment by phongkhuu115** [comment]
Turn out, we can use relative path, and make it easy using `wp_make_link_relative` ([docs](https://developer.wordpress.org/reference/functions/wp_make_link_relative/))

The URL of files choosing from the media popup looks like this: 

```
https://example.com/wp-content/uploads/folder1/folder2/image.png
```

After using the above function:

```
/wp-content/uploads/folder1/folder2/image.png
```

I haven't tested changing the site URL case, but with the normal case, it still works. The logo is just some random image.

![image](https://github.com/daomapsieucap/fiber-admin/assets/80519358/46a9c0cc-fa29-4cc4-b835-80d0f2d3759a)

![image](https://github.com/daomapsieucap/fiber-admin/assets/80519358/5500a0ae-2108-4276-9342-8b3eace4585b)

I'm confident that this solution will work even if the site URL change.

I'm going to test on my local machine first for safety, then test with my lab site late

**Comment by phongkhuu115** [comment]
After doing some testing with changing the site URL, the previous solution of mine doesn't work as expected, because with other hosts, and other folders, only removing the `https://example.com` part will not work. 

But still, using a relative path is a reliable solution, with a bit of modification, making the directory completely relative, everything works. 

Because we're getting attachments from the media library, the attachments always be under the `/upload` folder. I'm thinking of getting the current upload directory using `wp_get_upload_dir()`. And build the path with `subdir` attribute, and the filename from the option box.

![image](https://github.com/daomapsieucap/fiber-admin/assets/80519358/4dd3dcad-7fcf-4268-82b1-184d2075115b)

 
![image](https://github.com/daomapsieucap/fiber-admin/assets/80519358/37265e2e-c958-4084-bb44-f33de0bdf228)

**Comment by phongkhuu115** [comment]
The relative path is still the best option. The reason that we can't retrieve the image via a relative path when WordPress's file moves to another folder/URL is that the request sometimes does not redirect properly. For example, when I move my site to a folder `dberr`, when I access the site via `http://example.com/dberr` the request sent is still `http://example.com/wp-content/...`

![image](https://github.com/daomapsieucap/fiber-admin/assets/80519358/cbb398f4-c2ad-4576-b2ad-6cee1cbe28e6)

While it supposes to be `/dberr/somepath`

![image](https://github.com/daomapsieucap/fiber-admin/assets/80519358/b489846c-50cf-478b-9bec-b2b5f0738f3d)

I'm trying to fix this issue. I may need a few more hours

**Comment by phongkhuu115** [comment]
I can think of a way to form an absolute URL instead of using a relative path. 

For example, if a site has the URL `https://example.com/dberr`, the request must be `https://example.com/dberr/wp-content/uploads` in order to load the images. Using `../wp-content` will make the URL fall out of the subdirectory. Result in `https://example.com/wp-content/uploads` which will not be going to work.

Using PHP's constant, we can form an absolute URL in all cases since we know that the images will always be in `wp-content/uploads` folder whenever users select it in the media selector.

Using `__DIR__` we will get the `maindirectory/subdirectory/wp-content`. Then I use `$_SERVER['DOCUMENT_ROOT']` to get rid of the `maindirectory` since that part is going to be changed. Then use `"https://" . $_SERVER['HTTP_HOST']` to get the `https://example.com`.
```
"https://" . $_SERVER['HTTP_HOST'] . explode($_SERVER['DOCUMENT_ROOT'], __DIR__)[1]
```

Then in the function which I wrote before, I just need to get the path with `uploads` folder.
