### ISSUE TITLE
Clean image file names

### ISSUE THREAD

**Issue by daomapsieucap** [daomapsieucap/fiber-admin#13]
It's great to have the feature to format the image file name into browser and server-friendly, non-accent characters. 

There are many customers won't have enough basic knowledge about renaming the file name before uploading it to Media Library, we will help them cover this case. The case often happens for Vietnamese customers especially.

For example: The file name "Báo-cáo-thường-niên-2023.pdf" should be converted to "bao-cao-thuong-nien-2023.pdf" automatically.

For this feature, there should be a setting where admin can choose to turn on / off in CMS (default value is on).

**Comment by phongkhuu115** [comment]
WordPress already has its built-in sanitizing filename. But it's not good enough. 

Case failed:

- [ ] "ÐÕçument full of $$$.pdf" -> "DOcument-full-of-.pdf" (remaining 1 dash at the end)
- [ ] "Really%20Ugly%20Filename-_-That_-_Is_Too Common…..png" -> "Really20Ugly20Filename-_-That_-_Is_Too-Common….png.pdf" (too many special chars & dots remaining)
- [ ] "Báo-cáo-thường-niên-2023.pdf" -> "Bao-cao-thuong-nien-2023.pdf" (the B still uppercase)

So we still need to write our own setting.

**Comment by phongkhuu115** [comment]
From [this ticket](https://core.trac.wordpress.org/ticket/50855). Their developers had added logic for `%20` and `+`, but in [this change set](https://core.trac.wordpress.org/changeset/35122) we can see that `%` and `+` is considered as special chars. 

In the code of `sanitize_file_name(), we can see the char array stay the same since: 
![image](https://github.com/daomapsieucap/fiber-admin/assets/80519358/72c43672-6662-4c56-a895-7222fedf9b3b)

And the logic to replace special char run before the replacement of `%20`, so that causes the bug: `%` was stripped but leaving the `20`
![image](https://github.com/daomapsieucap/fiber-admin/assets/80519358/16efd28b-45f3-479b-aa69-6aae05c0ebd7)

So I think we need to hook into the `sanitize_file_name` filter to handle that case ourselves.

**Comment by daomapsieucap** [comment]
@phongkhuu115 : We still have the incorrect case when the file name has an encoded URL, for example:
`https%3A%2F%2Fgithub.com%2F.pdf` --> `https-3a-2f-2fgithub-com-2f.pdf` which doesn't make sense since we do have the case `Really%20Ugly%20Filename--That-Is_Too Common…..png`.

Please try to check this case. Thanks!

**Comment by phongkhuu115** [comment]
@daomapsieucap: I have finished with the case you mentions above. I have updated it so it can get rid of every urlencoded char. Can you please check it out again, thank you!!
