### ISSUE TITLE
Auto set attachment metadata

### ISSUE THREAD

**Issue by daomapsieucap** [daomapsieucap/fiber-admin#16]
In Fiber Admin > Misc, we do have settings to Auto set image meta. It's the feature to prevent the admin forget to input the image meta because it's related to the required `alt` attribute for `img` tag. 

![Screenshot_332](https://github.com/daomapsieucap/fiber-admin/assets/61570169/ed42742f-e566-484f-9b4a-8e2a2050b08e)

Fiber Admin will convert the file name to Image Title (as readable text) with the enabled option.

After some updates, especially with #13, the function to set `alt` attribute is not working properly.

Requirement:
- Move this option to a new group called Attachment.
- We will handle the metadata file for the image and pdf, doc, docx...
- Check and fix the issue with wrong metadata set.

**Comment by phongkhuu115** [comment]
@daomapsieucap From what I learned:
1. Since 2.9.0, when an attachment is inserted, the function `wp_insert_post` ([ref](https://developer.wordpress.org/reference/functions/wp_insert_post/)) is called, and `post_title`([ref](https://developer.wordpress.org/reference/functions/wp_strip_all_tags/)) field is handled with only 1 function `wp_strip_all_tags`

2. Because the function already exists, so I make Setting Metadata automatic and remove options in the admin site
